// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PD_212_MVC_Data;

#nullable disable

namespace PD_212_MVC_Classwork.Migrations
{
    [DbContext(typeof(AcademyContext))]
    [Migration("20241120162506_AddImageColumnInTeachersTable")]
    partial class AddImageColumnInTeachersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PD_212_MVC_Classwork.Models.Direction", b =>
                {
                    b.Property<byte>("direction_id")
                        .HasColumnType("tinyint");

                    b.Property<string>("direction_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("direction_id");

                    b.ToTable("Directions");
                });

            modelBuilder.Entity("PD_212_MVC_Classwork.Models.DirectionsDisciplinesRelation", b =>
                {
                    b.Property<byte>("direction")
                        .HasColumnType("tinyint");

                    b.Property<short>("discipline")
                        .HasColumnType("smallint");

                    b.HasKey("direction", "discipline");

                    b.HasIndex("discipline");

                    b.ToTable("DirectionsDisciplinesRelation");
                });

            modelBuilder.Entity("PD_212_MVC_Classwork.Models.Discipline", b =>
                {
                    b.Property<short>("discipline_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("discipline_id"));

                    b.Property<string>("discipline_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("number_of_lessons")
                        .HasColumnType("tinyint");

                    b.HasKey("discipline_id");

                    b.ToTable("Disciplines");
                });

            modelBuilder.Entity("PD_212_MVC_Classwork.Models.Group", b =>
                {
                    b.Property<int>("group_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("group_id"));

                    b.Property<byte>("direction")
                        .HasColumnType("tinyint");

                    b.Property<string>("group_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("group_id");

                    b.HasIndex("direction");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("PD_212_MVC_Classwork.Models.Student", b =>
                {
                    b.Property<int>("stud_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("stud_id"));

                    b.Property<DateTime>("birth_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("group")
                        .HasColumnType("int");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("middle_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("stud_id");

                    b.HasIndex("group");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("PD_212_MVC_Classwork.Models.Teacher", b =>
                {
                    b.Property<int>("teacher_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("teacher_id"));

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("birth_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("middle_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("work_since")
                        .HasColumnType("datetime2");

                    b.HasKey("teacher_id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("PD_212_MVC_Classwork.Models.TeachersDisciplinesRelation", b =>
                {
                    b.Property<int>("teacher")
                        .HasColumnType("int");

                    b.Property<short>("discipline")
                        .HasColumnType("smallint");

                    b.HasKey("teacher", "discipline");

                    b.HasIndex("discipline");

                    b.ToTable("TeachersDisciplinesRelation");
                });

            modelBuilder.Entity("PD_212_MVC_Classwork.Models.DirectionsDisciplinesRelation", b =>
                {
                    b.HasOne("PD_212_MVC_Classwork.Models.Direction", "Direction")
                        .WithMany("Disciplines")
                        .HasForeignKey("direction")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PD_212_MVC_Classwork.Models.Discipline", "Discipline")
                        .WithMany()
                        .HasForeignKey("discipline")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Direction");

                    b.Navigation("Discipline");
                });

            modelBuilder.Entity("PD_212_MVC_Classwork.Models.Group", b =>
                {
                    b.HasOne("PD_212_MVC_Classwork.Models.Direction", "Direction")
                        .WithMany("Groups")
                        .HasForeignKey("direction")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Direction");
                });

            modelBuilder.Entity("PD_212_MVC_Classwork.Models.Student", b =>
                {
                    b.HasOne("PD_212_MVC_Classwork.Models.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("group")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("PD_212_MVC_Classwork.Models.TeachersDisciplinesRelation", b =>
                {
                    b.HasOne("PD_212_MVC_Classwork.Models.Discipline", "Discipline")
                        .WithMany()
                        .HasForeignKey("discipline")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PD_212_MVC_Classwork.Models.Teacher", "Teacher")
                        .WithMany("Disciplines")
                        .HasForeignKey("teacher")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("PD_212_MVC_Classwork.Models.Direction", b =>
                {
                    b.Navigation("Disciplines");

                    b.Navigation("Groups");
                });

            modelBuilder.Entity("PD_212_MVC_Classwork.Models.Group", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("PD_212_MVC_Classwork.Models.Teacher", b =>
                {
                    b.Navigation("Disciplines");
                });
#pragma warning restore 612, 618
        }
    }
}
